### ISSUE TITLE
About Passive Event Listeners

### ISSUE THREAD

**Issue by AngusFu** [AlloyTeam/AlloyTouch#11]
## Description 

1. Chrome Device Mode
2. Chrome version tested:
    - Chrome/54.0.2840.87
    - Chrome Canary: Chrome/56.0.2916.0
3. File Version: alloy_touch.js latest（0.1.3）.

## Problem

![image](https://cloud.githubusercontent.com/assets/8180186/21255182/31d6bef6-c3a5-11e6-8d8e-d2849004bf09.png)

## Reference

According to the [given link](https://www.chromestatus.com/features/5093566007214080)

> AddEventListenerOptions defaults passive to false. We propose sometimes defaulting this to true in **some "document level" scenarios**. Specifically if an event listener is added to the document, body, or window and is a scroll blocking (touchstart, touchmove) listener it will be have its default to be true.If the value is explicitly provided in the AddEventListenerOptions it will continue having the value specified by the page.This is behind a flag starting in Chrome 54.

## Reproduce

Open [http://alloyteam.github.io/AlloyTouch/example/carousel.html](http://alloyteam.github.io/AlloyTouch/example/carousel.html) on a Chrome 54+ browser  or Chrome Canary, and enable device mode.

**Comment by kmdjs** [comment]
:+1:  how to fix it?

**Comment by AngusFu** [comment]
There is a `bind` function attaching events to `window`  and `document`. Change the 3rd parameter `false` to `{ passive: false, capture: false }` will _temporarily_ solve this problem. But this seems a little dirty and is against the initial purpose for Passive Events.

**Comment by kmdjs** [comment]
retry,  fixed~~. https://github.com/AlloyTeam/AlloyTouch/commit/ecb3324022cbde78919f1095d18d2d180027a12d

**Comment by AngusFu** [comment]
A good solution.

**Comment by AngusFu** [comment]
According to [docs on MDN](https://developer.mozilla.org/en/docs/Web/API/EventTarget/addEventListener), when `passive` is `true`, you can never call `preventDefault`.

According to [chromestatus](https://www.chromestatus.com/features/5093566007214080), listeners of `document` and `window` by default look `passive` as `true`.

![image](https://cloud.githubusercontent.com/assets/8180186/21261182/d471720e-c3c4-11e6-9daf-aa0561ea07a4.png)

![image](https://cloud.githubusercontent.com/assets/8180186/21261282/56290e9c-c3c5-11e6-91b3-a17ed95863b5.png)

So perhaps this issue needs furthure research as `Passive Events` evolves.

**Comment by kmdjs** [comment]
> is against the initial purpose for Passive Events.

dynamic binding event can fix it. so..  fix it ? :) 
https://github.com/AlloyTeam/AlloyTouch/commit/613e1ae73812d591c32f7b98478b4b7e70800a73

many thanks~~ :+1:

**Comment by AngusFu** [comment]
DONE! 👍 👍 👍 

I think the screenshot bellow may help us understand Passive Event Listeners better. So just paste it!

![image](https://cloud.githubusercontent.com/assets/8180186/21263853/08f3b96a-c3d4-11e6-8aa0-4593aac2f40f.png)
