### ISSUE TITLE
使用transformJS时，希望像CSS那样，属性值的先后顺序会造成影响，要怎么做？

### ISSUE THREAD

**Issue by larry011** [AlloyTeam/AlloyTouch#24]
比如说我想先`rotateX(45deg)`，再`translateZ(100px)`，如果直接用transformJS写 `el.roateX =45;el.translateZ = 100` 的话，结果是先translateZ，再rotate的。请问有什么办法可以像CSS那样？

**Comment by kmdjs** [comment]
不可以。transformjs的管线顺序是固定的。因为固定管线也是可以实现任意效果，所以不支持这种顺序影响结果的设计。

**Comment by larry011** [comment]
那能说下tranformJS的固定管线是什么吗？我使用经验是 `translateZ`是要先于其他属性的，其他还希望你能补充下

**Comment by kmdjs** [comment]
这里： https://github.com/AlloyTeam/AlloyTouch/blob/master/transformjs/transform.js#L95-L130

**Comment by larry011** [comment]
谢谢！
