### ISSUE TITLE
在Vue实例里面怎么使用to方法。

### ISSUE THREAD

**Issue by ToPeas** [AlloyTeam/AlloyTouch#28]
具体怎么实现用alloytouch来写一个带tabs的navigation。

**Comment by kmdjs** [comment]
嗯嗯，@zD98  正在开发ing 。

**Comment by NQYX-Scientist** [comment]
请问现在这个问题开发好了吗

**Comment by dntzhang** [comment]
zD98 已离职...

**Comment by zD98** [comment]
因为to方法是通过alloytouch的实例手动调用的
目前可以通过this.$el.__alloytouch_handle这种方式拿到alloytouch的实例
之后我会添加一个接口函数，getInstance，返回alloytouch的实例，之后可以在vue mounted后拿到实例
会在这两天解决

**Comment by zD98** [comment]
现在可以通过一个语法糖拿到实例
`
<div v-alloytouch="{...methods: {initAlloyTouch}}"></div>
`
`{
...
methods: {
    initAlloyTouch(handle){
        this.handleAlloyTouch = handle;
    }
}
}
`

**Comment by NQYX-Scientist** [comment]
非常感谢

**Comment by meiminjun** [comment]
请问一下，能不能增加一个配置项，去除这个滚动动画啊？ 
因为当我滑动到底部，再点击类似排序的按钮发起请求的时候，没有那么多数据时候，会一直停留在滑动的当前位置（已经到底部了），用to的方法解决，先滚动到顶部再请求，但是会有滚动动画，能不能加个参数去除这个动画? 有什么办法可以解决？
