### ISSUE TITLE
使用两次Transform会变模糊

### ISSUE THREAD

**Issue by Sioxas** [AlloyTeam/AlloyTouch#37]
如果一个元素使用了Transform，在其子元素上使用Transform会变模糊

**Comment by kmdjs** [comment]
@Sioxas 都打开了透视投影还是关闭了？

**Comment by Sioxas** [comment]
关闭后不模糊了，透视投影的作用是什么呀？

**Comment by kmdjs** [comment]
http://alloyteam.github.io/AlloyTouch/transformjs/ @Sioxas  看文档

**Comment by Sioxas** [comment]
明白了，O(∩_∩)O谢谢
