### ISSUE TITLE
触摸元素，惯性滚动中，设置translateY为0，闪屏

### ISSUE THREAD

**Issue by Frozen-boy** [AlloyTeam/AlloyTouch#49]
三个选项卡，选项卡点击事件为滚动到顶部translataY=0，在运动惯性滚动中点击了这个tab，会到0然后瞬间回到惯性滚动位置，有好的思路没有？点击的时候终止这个惯性滚动

**Comment by Frozen-boy** [comment]
已解决，跟css样式有关

**Comment by dntzhang** [comment]
@Frozen-boy 话说怎么解决的。最近在搞[omi](https://github.com/AlloyTeam/omi) 。还没来搞这个

**Comment by dntzhang** [comment]
@Frozen-boy ok~~

**Comment by FrozenByzz** [comment]
@dntzhang 抱歉，现在才看到，我解决的方法是把这个触摸的元素也放到，touch层里，这样点击这个元素的时候也会触发touch，滚动就会停住，然后变为0

**Comment by dntzhang** [comment]
ok。明白
