### ISSUE TITLE
css3transform NPM包有多余内容，可否清理一下？

### ISSUE THREAD

**Issue by imyzf** [AlloyTeam/AlloyTouch#68]
刚刚用OmniDiskSweeper扫了一下自己的工程，发现css3transform竟然有60MB，都是被react/example/node_modules占用的

![image](https://user-images.githubusercontent.com/8298849/26868214-cf6ba5f0-4b9a-11e7-93c0-0eb609f8057f.png)

刚开始还以为是自己的NPM出问题了，后来发现下载的就是这么大：https://registry.npmjs.org/css3transform/-/css3transform-1.1.5.tgz

**Comment by dntzhang** [comment]
额，多谢。已经清理并提交npm~~
