### ISSUE TITLE
不支持 Firefox ？

### ISSUE THREAD

**Issue by solarcellsky** [AlloyTeam/AlloyTouch#74]
官方 Demo http://alloyteam.github.io/AlloyTouch/full_page/ Firefox 无法切换页面。

**Comment by dntzhang** [comment]
应该是鼠标滚轮事件没有兼容~

**Comment by solarcellsky** [comment]
但是控制台并没有报任何错误或警告。

**Comment by solarcellsky** [comment]
修改了代码，是那块判断的问题
`if (type === "mousewheel" && document.mozHidden !== undefined)`
修改后
`// fix MouseScroll on Firefox
    var u = navigator.userAgent.toLowerCase();
    var isFirefox = u.indexOf('firefox') > -1;
    var addEvent =  function(el, type, fn, capture) {
        if (type === "mousewheel" && isFirefox) {
            type = "DOMMouseScroll";
        }
        el.addEventListener(type, function(e) {
            var evt = e || window.event
            var type = evt.type;
            if (type == "DOMMouseScroll" || type == "mousewheel") {
                evt.delta = evt.wheelDelta ? evt.wheelDelta / 120 : -(evt.detail || 0) / 3;
            }

            if (evt.delta) {
                fn.call(this, evt);
            }
        }, capture || false);
    };`

**Comment by dntzhang** [comment]
提个 pr来我合进去？

**Comment by solarcellsky** [comment]
刚刚提了。
