### ISSUE TITLE
请问 alloytouch 里面我包裹一个swiper,我现在拖动里面的swiper，外面会有微妙的滚动，怎么阻止外面alloytouch 滚动

### ISSUE THREAD

**Issue by joyhao** [AlloyTeam/AlloyTouch#87]
请问 alloytouch 里面我包裹一个swiper,我现在拖动里面的swiper，外面会有微妙的滚动，怎么阻止外面alloytouch 滚动

swiper 是左右滚动
alloytouch  是上下滚动

**Comment by dntzhang** [comment]
bindSelf 

touchStart:function(evt){
--
  | evt.stopPropagation();
  | },
  | touchMove:function(evt){
  | evt.stopPropagation();
  | },
  | bindSelf:true,

**Comment by joyhao** [comment]
外部用的alloytouch  ，内部里面没有用alloytouch 是用的swipe额

**Comment by dntzhang** [comment]
那你看下 swiper 怎么 bindSelf 和 stopPropagation

**Comment by joyhao** [comment]
bindSelf   是什么   配置你们好像没有注释

**Comment by joyhao** [comment]
@dntzhang 谢谢大哥提供思路，可以了
