### ISSUE TITLE
AlloyTouch 每次滚到底部会掉2次接口

### ISSUE THREAD

**Issue by joyhao** [AlloyTeam/AlloyTouch#88]
AlloyTouch 每次滚到底部会掉2次接口，怎么解决

**Comment by havingmeaning** [comment]
使用节流行数！

**Comment by havingmeaning** [comment]
节流函数

**Comment by havingmeaning** [comment]
然后设置一下开关

**Comment by joyhao** [comment]
调用的接口的时候  使用节流函数吗 ，也就是在change 判断下拉的时候

**Comment by havingmeaning** [comment]
其实，也不用节流函数，只要设置好 开关就可以了，比如  定义一个loading ,如果loading为 true的时候，就不用继续拉去数据，等拉完数据的时候，loading设置为 false

**Comment by joyhao** [comment]
v <=  _self.min + 5 && !loading

有判断额

**Comment by havingmeaning** [comment]
![image](https://user-images.githubusercontent.com/6167593/34146461-1757b98e-e4d5-11e7-9fc6-3611a61dfff5.png)
我是这样玩的，

**Comment by havingmeaning** [comment]
setTimeout是模拟ajax用的

**Comment by havingmeaning** [comment]
哦，这个只是用来测试的

**Comment by joyhao** [comment]
那你一般设置多少

**Comment by havingmeaning** [comment]
我一般是设置500
你可以封装一个 scroll，这样不用每次都去写 scrollEnd的判断了
![image](https://user-images.githubusercontent.com/6167593/34146664-dd2a0d6a-e4d5-11e7-8117-84c0d598236f.png)

**Comment by joyhao** [comment]
window.alloyTouch1.change=function (v) {
                var _self=this;
                if(v >= 0){
                    tipNews.addClass('none');
                    tipNews.data('num', 1);
                    $(".show-text-new").text(1);
                }
                if (v <=  _self.min + 5 && !loading) {
                    loading = true;
                   setTimeout(function(){
                        vm.infiniteData(WHD.ApiAddress.GetPostComments, couData,function (items) {
                            if(items === [] || items.length <= 0) {
                                $('.loading-more').text('没有数据了').removeClass('none');
                                return false;
                            }else{
                                $('.loading-more').text('正在加载中 ...').removeClass('none');
                            }
                            vm.infiniteArr=vm.infiniteArr.concat(items);
                            loading = false;
                            _self.reastMin();
                            couData.page++;
                        });
                   },2000)
                   
                }

**Comment by joyhao** [comment]
加了一个settimeout  不过还是一样
