### ISSUE TITLE
AlloyTouch  在 vue 中使用 ，每次下拉加载数据，就会自动滚动到 顶部去，是怎么回事

### ISSUE THREAD

**Issue by joyhao** [AlloyTeam/AlloyTouch#94]
`AlloyTouch  在 vue 中使用 ，每次下拉加载数据，就会自动滚动到 顶部去，是怎么回事`

<template>
  <div class="photo">
    <div id="photoWrapper" v-alloytouch="{options: options, methods:{initAlloyTouch: initAlloyTouch,touchMove:touchMove}, min:min, max: max}">
      <div id="photoScroller" class="alloytouch-target tranform">
        <ul class="recommends">
         
          <li v-for="item in items">{{item}}</li>
        </ul>
      </div>
    </div>
  </div>
</template>
<script>
    import Vue from 'vue'
    import { mapMutations } from 'vuex'
    import { mapState } from 'vuex'
    import { mapGetters } from 'vuex'
    import { mapActions } from 'vuex'
    import aollyTouch1 from 'alloytouch/vue/alloy_touch.vue'

    Vue.use(aollyTouch1)
    export default {
        data() {
            return {
              alloy:{},
              items:[1,2,3,4,5,6,7,8,9,10],
              options: {
                touch:"#photoWrapper",//反馈触摸的dom
                vertical: true,//不必需，默认是true代表监听竖直方向touch
                target: '#photoScroller', //运动的对象
                property: "translateY",  //被滚动的属性
                sensitivity: .65,//不必需,触摸区域的灵敏度，默认值为1，可以为负数
                factor: .75,//不必需,表示触摸位移与被运动属性映射关系，默认值是1
                bindSelf: false,
                maxSpeed: .5, //不必需，触摸反馈的最大速度限制
              },
              min: 0,
              max: 0,
              distance:0,
              handleAlloyTouch: null
            }
        },
        mounted() {
          const vm = this;
          vm.triggerDispatch("recommends");
          vm.alloy.scroller =  document.querySelector("#photoScroller");
          vm.alloy.footer =  document.querySelector(".footer");
          vm.alloy.loading = false;
          document.addEventListener("touchmove", function (evt) {
            evt.preventDefault();
          }, false);
        },
        methods: {
          initAlloyTouch(handle){
            const vm = this;
            vm.handleAlloyTouch = handle;
            vm.handleAlloyTouch.touchStart = function () {
              vm.resitMin();
            };
            vm.handleAlloyTouch.change = function(v){
              vm.distance = v ;
              if (v&&v <= vm.handleAlloyTouch.min + 5 && !vm.alloy.loading) {
                vm.alloy.loading = true;
                vm.loadMore();
              }
            }
          },
          touchMove(e){
            const vm = this;
            //e.preventDefault();
            /*if (e.changedTouches[0].pageY <= 0) {
             // vm.handleAlloyTouch.to(vm.handleAlloyTouch.min,1000);
            }*/
          },
          loadMore() {
            const  vm = this;
            let type = vm.$route.params.type;
            setTimeout(function () {
              for(var i = 0 ;i<3;i++){
                vm.items.push(Math.random());
              }
              //vm.triggerDispatch("recommends");
              vm.alloy.loading = false;
              vm.resitMin();
            },500)
          },
          resitMin() {
            const  vm = this;
            let scrollHeight = parseInt(getComputedStyle(vm.alloy.scroller).height);
            let footerHeight = parseInt(getComputedStyle(vm.alloy.footer).height);
            if(scrollHeight < window.innerHeight  + footerHeight){
              vm.handleAlloyTouch.min = 0;
            }else{
              vm.handleAlloyTouch.min = -1 * scrollHeight + window.innerHeight  - footerHeight*2
            }
          },
          triggerDispatch(type){
            const vm = this;
            switch (type){
              case "recommends":
                //vm.$store.dispatch("actImagesList",{type:type});
                break;
              default :console.log("没有对象类型");break;
            }

          },
          load(){

          }
        },
        computed: {
          ...mapGetters({
           getImagesList:'getImagesList',
          }),
        },
        watch: {
        },
        components: {

        },
    }
</script>
<style lang="scss">
  .recommends{
    li{
      margin-bottom:.3rem;
      padding:.2rem .15rem;
      text-align: center;
    background:#fff;
      a{
        display: block;
        width: 100%;
        text-align: center;
        img{
          max-width: 100%;

        }
      }
    }
  }

  #photoWrapper {
    position: absolute;
    z-index: 1;
    top:0;
    bottom: 0;
    left: 0;
    width: 100%;
    background: #ccc;
    overflow: hidden;
  }

  #photoScroller{
    position: absolute;
    z-index: 1;
    width: 100%;
  }
</style>

**Comment by havingmeaning** [comment]
我估计是 min的设置有问题
