### ISSUE TITLE
能否在tap里使用to

### ISSUE THREAD

**Issue by clll7** [AlloyTeam/AlloyTouch#95]
在调用to之后似乎又触发了end，所以又回到了原位，没法to到想要的位置。
如果延时200毫秒再调用to，就可以。

![image](https://user-images.githubusercontent.com/6949822/33592354-7ff64548-d9c5-11e7-842c-3bb6d8bf6983.png)

**Comment by clll7** [comment]
似乎是同时用了fastclick导致的问题

**Comment by havingmeaning** [comment]
个人感觉，你不应该在 tap中去做这个，应该是在 touchend那个事件那边去做

**Comment by clll7** [comment]
@havingmeaning 感谢
